#!/bin/bash

echo "*********************************************************"
echo "Running git pre-push hook. Running Detekt... "
echo "*********************************************************"

# run spotless apply
ROOT=$(git rev-parse --show-toplevel)
cd $ROOT/android
./gradlew --no-configuration-cache detektAll

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    # Add staged file changes to git
    for file in $stagedFiles; do
      if test -f "$file"; then
        git add $file
      fi
    done
    #Exit
    exit 0
else
    echo "*********************************************************"
    echo 1>&2 "Detekt found violations"
    echo "*********************************************************"
    #Exit
    exit 1
fi