#!/bin/bash

GIT_DIR=$(git rev-parse --git-dir)
ROOT=$(pwd)

echo "Installing pre-commit hook"
echo
mkdir -p "${GIT_DIR}/hooks/"
cp "${ROOT}/pre-commit" "${GIT_DIR}/hooks/pre-commit" && chmod +x "${GIT_DIR}/hooks/pre-commit"

cat <<-EOF
Checking the following settings helps avoid miscellaneous issues:
  * Settings -> Editor -> General -> Remove trailing spaces on: Modified lines
 and Java)
EOF