#!/bin/bash

GIT_DIR=$(git rev-parse --git-dir)
ROOT="$(git rev-parse --show-toplevel)/android"

echo "Installing pre-push hook"
echo
mkdir -p "${GIT_DIR}/hooks/"
cp "${ROOT}/tools/pre-push" "${GIT_DIR}/hooks/pre-push" && chmod +x "${GIT_DIR}/hooks/pre-push"

cat <<-EOF
Checking the following settings helps avoid miscellaneous issues:
  * Settings -> Editor -> General -> Remove trailing spaces on: Modified lines
 and Java)
EOF